#!/bin/bash
set -eo pipefail

# get current working dir
CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# load libs
. "$CURRENT_DIR/lib/scripts/constants.bash"
. "$CURRENT_DIR/lib/scripts/shared.bash"
. "$CURRENT_DIR/lib/scripts/roborover.bash"
. "$CURRENT_DIR/lib/scripts/setup.bash"

function help() {
  echo "$0 [command | [subcommand]] <options>"
  printf "\nCommands:\n\n"
  echo "$0 deploy [infrastructure|basesestation] <environment> <region> (optional)"
  echo "$0 roveros [start|stop]"
  echo "$0 refresh"
  echo "$0 setup"
  echo "$0 command [pan|tilt|forward|backward|left|right|stop|drive_cm|drive_deg|speed|image] <value>"
  echo "$0 help"
}

# draw art
ascii

# check dependencies
check_dependencies

# evaluate input

while [ "$#" -gt 0 ]; do
  case "$1" in

    deploy) 
          case "$2" in 
            infrastructure|infra)   
                deploy_roborover $3 $4
                shift 4;;
            basestation|base)  
                deploy_basestation $3 $4
                shift 4;;
            *) 
                log "validate" "unknown option: $2" "fail" >&2;
                exit 2;;
          esac;;

    roveros) 
          case "$2" in 
            start)   
                start_roveros
                shift 2;;
            stop)  
                stop_roveros
                shift 2;;
            stream)
                stream_rover
                shift 2;;
            *) 
                log "validate" "unknown option: $2" "fail" >&2;
                exit 2;;
          esac;;
    streaming) 
          case "$2" in 
            start)   
                start_stream_rover
                shift 2;;
            stop)  
                stop_stream_rover
                shift 2;;
            *) 
                log "validate" "unknown option: $2" "fail" >&2;
                exit 2;;
          esac;;

    refresh)      setup_refresh $2 $3
                shift 3;;

    setup)      setup_roborover $2 $3
                shift 3;;

    command|cmd)

      case "$2" in

        pan)        validate
                    run_api "pan" $3
                    shift 3;;

        tilt)       validate
                    run_api "tilt" $3
                    shift 3;;

        forward)    validate
                    run_api "forward" $3
                    shift 3;;

        backward)   validate
                    run_api "backward" $3
                    shift 3;;

        stop)       validate
                    run_api "stop" $3
                    shift 3;;

        left)       validate
                    run_api "left" $3
                    shift 3;;

        right)      validate
                    run_api "right" $3
                    shift 3;;

        drive-cm)   validate
                    run_api "drive_cm" $3
                    shift 3;;

        drive-deg)  validate
                    run_api "drive_degrees" $3
                    shift 3;;

        speed)      validate
                    run_api "set_speed" $3
                    shift 3;;

        image|img)      validate
                    run_api "image" 0
                    shift 3;;

        *) 
            log "validate" "unknown command: $2" "fail" >&2;
            exit 2;;
      esac;;

    help)
                help
                shift 2;;
    *) 
        log "validate" "unknown option: $1" "fail" >&2;
        exit 1;;

  esac
done