#!/bin/bash
set -eo pipefail

# get current working dir
CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# load libs
. "$CURRENT_DIR/lib/scripts/constants.bash"
. "$CURRENT_DIR/lib/scripts/shared.bash"
. "$CURRENT_DIR/lib/scripts/roborover.bash"
. "$CURRENT_DIR/lib/scripts/setup.bash"

# draw art
ascii

# check dependencies
check_dependencies

# evaluate input

while [ "$#" -gt 0 ]; do
  case "$1" in

    deploy) 
          case "$2" in 
            infrastructure|infra)   
                deploy_roborover $3 $4
                shift 4;;
            basestation|base)  
                deploy_basestation $3 $4
                shift 4;;
            *) 
                log "validate" "unknown option: $2" "fail" >&2;
                exit 2;;
          esac;;

    roveros) 
          case "$2" in 
            start)   
                start_roveros
                shift 2;;
            stop)  
                stop_roveros
                shift 2;;
            *) 
                log "validate" "unknown option: $2" "fail" >&2;
                exit 2;;
          esac;;

    refresh)      setup_refresh $2 $3
                shift 3;;

    setup)      setup_roborover $2 $3
                shift 3;;

    pan)        validate
                run_api "pan" $2
                shift 2;;

    tilt)       validate
                run_api "tilt" $2
                shift 2;;

    forward)    validate
                run_api "forward" $2
                shift 2;;

    backward)   validate
                run_api "backward" $2
                shift 2;;

    stop)       validate
                run_api "stop" $2
                shift 2;;

    left)       validate
                run_api "left" $2
                shift 2;;

    right)      validate
                run_api "right" $2
                shift 2;;

    drive-cm)   validate
                run_api "drive_cm" $2
                shift 2;;

    drive-deg)  validate
                run_api "drive_degrees" $2
                shift 2;;

    speed)      validate
                run_api "set_speed" $2
                shift 2;;

    speed)      validate
                run_api "image" 0
                shift 2;;

    *) 
        log "validate" "unknown option: $1" "fail" >&2;
        exit 1;;

  esac
done