image-upload-recognition:
  handler: services/recognition/upload.handler
  # iamRoleStatementsName: roborover-image-upload-recognition-${self:provider.stage}
  # iamRoleStatements:
  #   - Effect: 'Allow'
  #     Action:
  #       - rekognition:*
  #     Resource: '*'
  #   - Effect: 'Allow'
  #     Action:
  #       - dynamodb:PutItem
  #       - dynamodb:UpdateItem
  #     Resource:
  #       - 'Fn::GetAtt': [ImageTable, Arn]
  events:
    - http:
        path: api/recognize
        method: post
        cors: true

image-get:
  handler: services/recognition/get.handler
  # iamRoleStatementsName: roborover-image-get-${self:provider.stage}
  # iamRoleStatements:
  #   - Effect: 'Allow'
  #     Action:
  #       - dynamodb:Query
  #       - dynamodb:Scan
  #       - dynamodb:GetItem
  #     Resource:
  #       - 'Fn::GetAtt': [ImageTable, Arn]
  events:
    - http:
        path: api/recognize
        method: get
        cors: true