service: rr-infra
#frameworkVersion: ">=1.1.0 <2.0.0"
# frameworkVersion: '^3.18.2'

plugins:
  - serverless-iam-roles-per-function
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    REGION: ${self:provider.region}
    TELEMETRY_TABLE: telemetry-${self:provider.stage}
    IMAGE_TABLE: images-${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchWriteItem
      Resource:
        - "Fn::GetAtt": [ TelemetryTable, Arn ]
        - "Fn::GetAtt": [ ImageTable, Arn ]
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:BatchWriteItem
      Resource:
        - "Fn::GetAtt": [TelemetryTable, Arn]
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource:
        - "Fn::GetAtt": [TelemetryTable, Arn]
    - Effect: 'Allow'
      Action:
        - rekognition:*
      Resource: '*'
    - Effect: 'Allow'
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource:
        - 'Fn::GetAtt': [ImageTable, Arn]
    - Effect: 'Allow'
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource:
        - 'Fn::GetAtt': [ImageTable, Arn]
    - Effect: 'Allow'     
      Action:
        - iot:DescribeEndpoint
      Resource: '*'
    - Effect: 'Allow'      
      Action:
        - iot:Publish
      Resource: '*'

functions:
  - ${file(./services/telemetry/functions.yml)}
  - ${file(./services/control/functions.yml)}
  - ${file(./services/recognition/functions.yml)}

resources:
  - ${file(./shared/resources.yml)}
  - ${file(./services/telemetry/resources.yml)}
  - ${file(./services/recognition/resources.yml)}